name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Metrics
        uses: lowlighter/metrics@v3.34.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ak-301
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_languages_details: percentage
          plugin_repositories: yes
          plugin_repositories_pinned: 4
          plugin_achievements: no

